# Task 3 Background

Today, credit is no longer limited to classical bank loans. The rise of e-commerce has increased the demand for new and more flexible credit solutions. The increased demand has been met by new companies from the fintech sector that offer easily accessible online loans to a wide audience. These new business models offer simple solutions, such as flexible payment schedules or buy-now-pay-later, that can be accessed with just a few clicks. 

Online merchants also need new ways to procure capital to manufacture their products, as they receive payment only after their product has been sold. In order to meet increasing demand, new credit offerings have emerged. Repayment of these loans is no longer based on a fixed schedule but instead depends directly on online sales. The loan is paid back in instalments with every sale, and thus payments depend directly on the sales volume. 

Predicting the future cash flows needed for the valuation of a portfolio consisting of these merchant loans is challenging. 

But you’re up for a challenge, right? 

Next stop: Zurich.

Our client is a large global online lending platform that provides loans to both consumers and merchants. These instruments are classified as assets on the balance sheet. 

Our audit colleagues have asked for our help to ensure the balance sheet values are correct. The value of the loan portfolio depends on future cash flows, which are stochastic. 

Our job is to ensure that the client’s portfolio has been valued correctly.

# Task and to-do

As you are supporting the audit colleagues with the audit for the year 2020, the value of the portfolio shall be determined as of 31 December 2020. For the valuation, you are free to use a tool of your choice (e.g. R, Python, Excel). The following steps will guide you through the valuation:

1. Inspect the historical data provided by the client. The data ranges from June 2019 until December 2020. Every month constitutes a vintage and the data includes the loan amount that was originated per vintage, as well as the repayments that have been observed up until and including December 2020 (the vintages are given as rows and the columns specify the period of the repayment).
2. Based on the provided data, compute the historical repayment percentages, i.e. every repayment’s share of the origination amount.
3. Compute the expected repayment percentages for all vintages over the lifetime of the loans. Details on how the expected repayment percentages are to be computed can be found in the attached assumptions PDF below.
4. From the expected repayment percentages, compute the forecasted cash flows using the origination amounts.
5. Using the assumed discount rate, derive the present value of the forecasted cash flows and of the portfolio. Don’t forget to convert the annual interest rate to a monthly interest rate.
6. The client’s estimate of the portfolio value was CHF 84’993’122.67. How close is this to your own estimate? Compute both the absolute and relative difference. Jakob tells you that the audit team considers any difference smaller than CHF 500’000 to be acceptable given the size of the portfolio. 
7. Based on the result of your valuation, conclude whether the difference to the client’s estimate falls below his threshold. 

Jakob notes: The portfolio value should be rounded to two decimal places. The slides can be simple as we'll use them internally first. Focus on correct solutions to set up the team with the right insights.

# Task 1

In [3964]:
import pandas as pd
from pathlib import Path

data = pd.read_csv(Path("Data.csv"), sep=';', header=[0], index_col=[0])

In [3965]:
data #Data is the

,Origination Amount,31.05.2019,30.06.2019,31.07.2019,31.08.2019,30.09.2019,31.10.2019,30.11.2019,31.12.2019,31.01.2020,...,31.03.2020,30.04.2020,31.05.2020,30.06.2020,31.07.2020,31.08.2020,30.09.2020,31.10.2020,30.11.2020,31.12.2020
31.05.2019,10018746.17,1443069.08,3332200.33,1328138.75,928085.74,736418.27,539403.31,427557.86,324459.32,237056.39,...,116684.68,92699.67,63399.66,53265.12,37121.13,29787.10,24524.90,18085.94,16581.01,11442.97
30.06.2019,10868379.04,0.00,1392751.60,3011884.91,1237868.70,970929.28,892351.83,668767.02,505612.59,419598.74,...,255222.42,198833.96,161996.73,138461.91,92346.68,79641.30,63457.44,52373.85,43374.70,37404.87
31.07.2019,10733932.61,0.00,0.00,1537650.24,2953335.55,1208316.08,879375.19,711016.84,658251.40,503465.03,...,302575.54,258652.52,191798.05,170027.54,127574.33,110301.21,89766.69,64746.84,61408.92,50312.70
31.08.2019,12558727.02,0.00,0.00,0.00,1617681.94,4082016.00,1387474.94,1247623.59,886293.35,694348.63,...,417223.56,336686.08,253556.20,200066.59,151859.74,109973.00,90228.14,70661.50,53102.83,47069.84
30.09.2019,14505071.44,0.00,0.00,0.00,0.00,1992242.84,3930445.60,1394620.78,1227905.58,939424.54,...,628429.48,589692.85,457299.31,323764.87,288152.28,239872.99,192246.98,171550.69,142575.97,116853.05
31.10.2019,15652952.20,0.00,0.00,0.00,0.00,0.00,2289453.76,4682354.31,1659503.89,1165897.09,...,763523.36,742787.97,558085.95,461806.22,358671.23,281881.11,241719.91,182730.05,144953.58,119260.10
30.11.2019,15107713.30,0.00,0.00,0.00,0.00,0.00,0.00,2162283.09,4637701.69,1576348.23,...,930720.35,697500.94,667277.73,547749.09,387987.02,309448.86,283876.04,215635.85,185516.45,141560.57
31.12.2019,17004745.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2402403.37,4947764.21,...,1245452.39,1116505.94,803590.21,724956.28,545397.33,458832.95,393971.01,333818.53,286831.44,216447.57
31.01.2020,16794379.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2502066.86,...,1505493.21,1182983.95,955821.48,846061.73,683116.81,560572.44,468203.76,349067.92,309854.99,267813.78
29.02.2020,19217205.82,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,6142911.08,1833677.81,1317065.75,1108494.37,918465.33,719913.69,587381.96,498801.31,371563.77,294941.22
31.03.2020,21628095.29,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,2843285.54,6228477.78,1585123.49,1425436.30,1110978.39,956265.05,815621.71,684971.52,644953.50,511673.76
30.04.2020,22334728.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,3332800.29,6476251.76,1747437.15,1419428.65,1072005.46,977346.88,836368.52,617274.49,547562.79
31.05.2020,22393345.39,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,3575896.21,7636995.58,1542705.08,1376501.77,1189742.70,888608.29,676918.44,626450.24
30.06.2020,24671655.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,3746372.58,8983764.16,1653631.68,1512916.37,1160275.72,945057.64,747172.11
31.07.2020,25478232.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,3470149.61,8030091.09,1612000.20,1357290.46,1178479.01,945964.38
31.08.2020,25878820.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,3510328.95,8374134.70,1564208.19,1362121.91,1098593.34
30.09.2020,25887161.41,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,3976808.32,7065477.24,1385481.66,1115017.68
31.10.2020,27699586.46,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3667678.21,8752706.73,1503544.68
30.11.2020,29872889.68,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4383982.78,8383025.07
31.12.2020,30482978.52,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4373830.97

In [3966]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 31.05.2019 to 31.12.2020
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Origination Amount  20 non-null     float64
 1   31.05.2019          20 non-null     float64
 2   30.06.2019          20 non-null     float64
 3   31.07.2019          20 non-null     float64
 4   31.08.2019          20 non-null     float64
 5   30.09.2019          20 non-null     float64
 6   31.10.2019          20 non-null     float64
 7   30.11.2019          20 non-null     float64
 8   31.12.2019          20 non-null     float64
 9   31.01.2020          20 non-null     float64
 10  29.02.2020          20 non-null     float64
 11  31.03.2020          20 non-null     float64
 12  30.04.2020          20 non-null     float64
 13  31.05.2020          20 non-null     float64
 14  30.06.2020          20 non-null     float64
 15  31.07.2020          20 non-null     float64
 16  31.08.2020          20 non-null     float64
 17  30.09.2020          20 non-null     float64
 18  31.10.2020          20 non-null     float64
 19  30.11.2020          20 non-null     float64
 20  31.12.2020          20 non-null     float64
dtypes: float64(21)
memory usage: 3.4+ KB

In [3967]:
data.describe()

,Origination Amount,31.05.2019,30.06.2019,31.07.2019,31.08.2019,30.09.2019,31.10.2019,30.11.2019,31.12.2019,31.01.2020,...,31.03.2020,30.04.2020,31.05.2020,30.06.2020,31.07.2020,31.08.2020,30.09.2020,31.10.2020,30.11.2020,31.12.2020
count,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,...,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01
mean,1.993947e+07,7.215345e+04,2.362476e+05,2.938837e+05,3.368486e+05,4.494961e+05,4.959252e+05,5.647112e+05,6.151066e+05,6.492985e+05,...,7.575761e+05,8.305650e+05,8.533581e+05,9.565448e+05,1.005886e+06,9.749524e+05,1.044697e+06,9.591175e+05,1.078137e+06,1.057797e+06
std,6.563824e+06,3.226801e+05,7.923004e+05,7.770531e+05,7.767479e+05,1.014007e+06,1.014547e+06,1.143841e+06,1.159722e+06,1.214030e+06,...,1.457239e+06,1.517052e+06,1.573937e+06,1.811136e+06,2.054033e+06,1.860876e+06,1.959497e+06,1.672878e+06,2.055731e+06,1.978896e+06
min,1.001875e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.144297e+04
25%,1.495705e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.784085e+04,6.717775e+04,8.318938e+04,6.918283e+04,1.222842e+05,1.186583e+05
50%,2.042265e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.859535e+05,2.287432e+05,2.226771e+05,2.619157e+05,3.234118e+05,2.956650e+05,3.389235e+05,3.414432e+05,3.407094e+05,4.033075e+05
75%,2.557838e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.841046e+05,6.243963e+05,6.793295e+05,7.152619e+05,7.556176e+05,...,8.053226e+05,8.362175e+05,8.416480e+05,9.116699e+05,9.665936e+05,9.852002e+05,1.030446e+06,9.565251e+05,1.003413e+06,9.841216e+05
max,3.048298e+07,1.443069e+06,3.332200e+06,3.011885e+06,2.953336e+06,4.082016e+06,3.930446e+06,4.682354e+06,4.637702e+06,4.947764e+06,...,6.142911e+06,6.228478e+06,6.476252e+06,7.636996e+06,8.983764e+06,8.030091e+06,8.374135e+06,7.065477e+06,8.752707e+06,8.383025e+06

# Task 2

In [3968]:
loans = data.copy()

In [3969]:
import numpy as np

column_names = np.array(loans.columns)[1:]
origination = loans["Origination Amount"]

for col in column_names:
    loans[col] = (loans[col] / origination)

In [3970]:
loans

,Origination Amount,31.05.2019,30.06.2019,31.07.2019,31.08.2019,30.09.2019,31.10.2019,30.11.2019,31.12.2019,31.01.2020,...,31.03.2020,30.04.2020,31.05.2020,30.06.2020,31.07.2020,31.08.2020,30.09.2020,31.10.2020,30.11.2020,31.12.2020
31.05.2019,10018746.17,0.144037,0.332597,0.132565,0.092635,0.073504,0.053839,0.042676,0.032385,0.023661,...,0.011647,0.009253,0.006328,0.005317,0.003705,0.002973,0.002448,0.001805,0.001655,0.001142
30.06.2019,10868379.04,0.000000,0.128147,0.277124,0.113896,0.089335,0.082105,0.061533,0.046521,0.038607,...,0.023483,0.018295,0.014905,0.012740,0.008497,0.007328,0.005839,0.004819,0.003991,0.003442
31.07.2019,10733932.61,0.000000,0.000000,0.143251,0.275140,0.112570,0.081925,0.066240,0.061324,0.046904,...,0.028189,0.024097,0.017868,0.015840,0.011885,0.010276,0.008363,0.006032,0.005721,0.004687
31.08.2019,12558727.02,0.000000,0.000000,0.000000,0.128809,0.325034,0.110479,0.099343,0.070572,0.055288,...,0.033222,0.026809,0.020190,0.015930,0.012092,0.008757,0.007184,0.005626,0.004228,0.003748
30.09.2019,14505071.44,0.000000,0.000000,0.000000,0.000000,0.137348,0.270970,0.096147,0.084654,0.064765,...,0.043325,0.040654,0.031527,0.022321,0.019866,0.016537,0.013254,0.011827,0.009829,0.008056
31.10.2019,15652952.20,0.000000,0.000000,0.000000,0.000000,0.000000,0.146263,0.299136,0.106019,0.074484,...,0.048778,0.047454,0.035654,0.029503,0.022914,0.018008,0.015442,0.011674,0.009260,0.007619
30.11.2019,15107713.30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.143124,0.306976,0.104341,...,0.061606,0.046169,0.044168,0.036256,0.025681,0.020483,0.018790,0.014273,0.012280,0.009370
31.12.2019,17004745.04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141278,0.290964,...,0.073241,0.065658,0.047257,0.042633,0.032073,0.026983,0.023168,0.019631,0.016868,0.012729
31.01.2020,16794379.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.148982,...,0.089643,0.070439,0.056913,0.050378,0.040675,0.033379,0.027879,0.020785,0.018450,0.015947
29.02.2020,19217205.82,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.319657,0.095419,0.068536,0.057682,0.047794,0.037462,0.030565,0.025956,0.019335,0.015348
31.03.2020,21628095.29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.131463,0.287981,0.073290,0.065907,0.051367,0.044214,0.037711,0.031670,0.029820,0.023658
30.04.2020,22334728.88,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.149221,0.289963,0.078239,0.063553,0.047997,0.043759,0.037447,0.027637,0.024516
31.05.2020,22393345.39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.159686,0.341039,0.068891,0.061469,0.053129,0.039682,0.030229,0.027975
30.06.2020,24671655.23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.151849,0.364133,0.067026,0.061322,0.047029,0.038305,0.030285
31.07.2020,25478232.23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.136201,0.315175,0.063270,0.053273,0.046254,0.037128
31.08.2020,25878820.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.135645,0.323590,0.060444,0.052635,0.042451
30.09.2020,25887161.41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.153621,0.272934,0.053520,0.043072
31.10.2020,27699586.46,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.132409,0.315987,0.054280
30.11.2020,29872889.68,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.146755,0.280623
31.12.2020,30482978.52,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.143484

In [3971]:
names = [f"month_{i+1}" for i in range(len(loans.columns) - 1)]

In [3972]:
loans = loans.set_axis(names, axis=0)

In [3973]:
col_names = ["Origination"] + names

In [3974]:
loans = loans.set_axis(col_names, axis=1)

In [3975]:
loans

,Origination,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,...,month_11,month_12,month_13,month_14,month_15,month_16,month_17,month_18,month_19,month_20
month_1,10018746.17,0.144037,0.332597,0.132565,0.092635,0.073504,0.053839,0.042676,0.032385,0.023661,...,0.011647,0.009253,0.006328,0.005317,0.003705,0.002973,0.002448,0.001805,0.001655,0.001142
month_2,10868379.04,0.000000,0.128147,0.277124,0.113896,0.089335,0.082105,0.061533,0.046521,0.038607,...,0.023483,0.018295,0.014905,0.012740,0.008497,0.007328,0.005839,0.004819,0.003991,0.003442
month_3,10733932.61,0.000000,0.000000,0.143251,0.275140,0.112570,0.081925,0.066240,0.061324,0.046904,...,0.028189,0.024097,0.017868,0.015840,0.011885,0.010276,0.008363,0.006032,0.005721,0.004687
month_4,12558727.02,0.000000,0.000000,0.000000,0.128809,0.325034,0.110479,0.099343,0.070572,0.055288,...,0.033222,0.026809,0.020190,0.015930,0.012092,0.008757,0.007184,0.005626,0.004228,0.003748
month_5,14505071.44,0.000000,0.000000,0.000000,0.000000,0.137348,0.270970,0.096147,0.084654,0.064765,...,0.043325,0.040654,0.031527,0.022321,0.019866,0.016537,0.013254,0.011827,0.009829,0.008056
month_6,15652952.20,0.000000,0.000000,0.000000,0.000000,0.000000,0.146263,0.299136,0.106019,0.074484,...,0.048778,0.047454,0.035654,0.029503,0.022914,0.018008,0.015442,0.011674,0.009260,0.007619
month_7,15107713.30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.143124,0.306976,0.104341,...,0.061606,0.046169,0.044168,0.036256,0.025681,0.020483,0.018790,0.014273,0.012280,0.009370
month_8,17004745.04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141278,0.290964,...,0.073241,0.065658,0.047257,0.042633,0.032073,0.026983,0.023168,0.019631,0.016868,0.012729
month_9,16794379.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.148982,...,0.089643,0.070439,0.056913,0.050378,0.040675,0.033379,0.027879,0.020785,0.018450,0.015947
month_10,19217205.82,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.319657,0.095419,0.068536,0.057682,0.047794,0.037462,0.030565,0.025956,0.019335,0.015348
month_11,21628095.29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.131463,0.287981,0.073290,0.065907,0.051367,0.044214,0.037711,0.031670,0.029820,0.023658
month_12,22334728.88,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.149221,0.289963,0.078239,0.063553,0.047997,0.043759,0.037447,0.027637,0.024516
month_13,22393345.39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.159686,0.341039,0.068891,0.061469,0.053129,0.039682,0.030229,0.027975
month_14,24671655.23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.151849,0.364133,0.067026,0.061322,0.047029,0.038305,0.030285
month_15,25478232.23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.136201,0.315175,0.063270,0.053273,0.046254,0.037128
month_16,25878820.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.135645,0.323590,0.060444,0.052635,0.042451
month_17,25887161.41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.153621,0.272934,0.053520,0.043072
month_18,27699586.46,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.132409,0.315987,0.054280
month_19,29872889.68,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.146755,0.280623
month_20,30482978.52,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.143484

# Task 3

### Assumptions
- Cash flows are assumed to be paid back by 30 months which is the total lifetime

In [3976]:
# Task 3
months = {f"month_{i}": float(0.000000) for i in range(21, 45)}
loans = loans.assign(**months)

In [3977]:
loans

,Origination,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,...,month_35,month_36,month_37,month_38,month_39,month_40,month_41,month_42,month_43,month_44
month_1,10018746.17,0.144037,0.332597,0.132565,0.092635,0.073504,0.053839,0.042676,0.032385,0.023661,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_2,10868379.04,0.000000,0.128147,0.277124,0.113896,0.089335,0.082105,0.061533,0.046521,0.038607,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_3,10733932.61,0.000000,0.000000,0.143251,0.275140,0.112570,0.081925,0.066240,0.061324,0.046904,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_4,12558727.02,0.000000,0.000000,0.000000,0.128809,0.325034,0.110479,0.099343,0.070572,0.055288,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_5,14505071.44,0.000000,0.000000,0.000000,0.000000,0.137348,0.270970,0.096147,0.084654,0.064765,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_6,15652952.20,0.000000,0.000000,0.000000,0.000000,0.000000,0.146263,0.299136,0.106019,0.074484,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_7,15107713.30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.143124,0.306976,0.104341,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_8,17004745.04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141278,0.290964,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_9,16794379.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.148982,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_10,19217205.82,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_11,21628095.29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_12,22334728.88,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_13,22393345.39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_14,24671655.23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_15,25478232.23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_16,25878820.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_17,25887161.41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_18,27699586.46,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_19,29872889.68,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
month_20,30482978.52,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3978]:
def p_i(i, p2, previous_sum):
    return max(p2 * np.log(1 + (1 -  (i - 1) / 30) * (1 - previous_sum)), 0)
    
def calcs(df, row_number):
    row = df.loc[f"month_{row_number}"][1:]
    historical_data = row[:21].tolist() 
    non_zero = [i for i in historical_data if i != 0]
    
    if len(non_zero) == 1:
        p1 = non_zero[0]
        p2 = p1 * 2
        non_zero.append(p2)
    else:
        p1, p2 = non_zero[:2]
    
    results = non_zero.copy()
    previous_sum = sum(results)
    
    start_predict = len(results)
    total_months = min(30, 45 - row_number)
    
    for i in range(start_predict, total_months):
        p = p_i(i, p2, previous_sum)
        results.append(p)
        previous_sum += p
    
    return results

In [3979]:
def new_rows(array):
    start_column = loans.columns.get_loc(f"month_{i}")
    end_column = start_column + len(array)
    print(f"month_{i}", start_column, end_column, len(array))
    loans.loc[f"month_{i}", loans.columns[start_column:end_column]] = array

In [3980]:
for i in range(1, 21):
    l = calcs(loans, i)
    new_rows(l)

month_1 1 31 30
month_2 2 32 30
month_3 3 33 30
month_4 4 34 30
month_5 5 35 30
month_6 6 36 30
month_7 7 37 30
month_8 8 38 30
month_9 9 39 30
month_10 10 40 30
month_11 11 41 30
month_12 12 42 30
month_13 13 43 30
month_14 14 44 30
month_15 15 45 30
month_16 16 45 29
month_17 17 45 28
month_18 18 45 27
month_19 19 45 26
month_20 20 45 25

In [3981]:
loans

,Origination,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,...,month_35,month_36,month_37,month_38,month_39,month_40,month_41,month_42,month_43,month_44
month_1,10018746.17,0.144037,0.332597,0.132565,0.092635,0.073504,0.053839,0.042676,0.032385,0.023661,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_2,10868379.04,0.000000,0.128147,0.277124,0.113896,0.089335,0.082105,0.061533,0.046521,0.038607,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_3,10733932.61,0.000000,0.000000,0.143251,0.275140,0.112570,0.081925,0.066240,0.061324,0.046904,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_4,12558727.02,0.000000,0.000000,0.000000,0.128809,0.325034,0.110479,0.099343,0.070572,0.055288,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_5,14505071.44,0.000000,0.000000,0.000000,0.000000,0.137348,0.270970,0.096147,0.084654,0.064765,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_6,15652952.20,0.000000,0.000000,0.000000,0.000000,0.000000,0.146263,0.299136,0.106019,0.074484,...,0.000322,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_7,15107713.30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.143124,0.306976,0.104341,...,0.000505,0.000327,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_8,17004745.04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.141278,0.290964,...,0.000884,0.000638,0.000413,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_9,16794379.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.148982,...,0.001234,0.000942,0.000680,0.000441,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_10,19217205.82,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001001,0.000781,0.000592,0.000425,0.000274,0.000000,0.000000,0.000000,0.000000,0.000000
month_11,21628095.29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001932,0.001546,0.001215,0.000926,0.000668,0.000433,0.000000,0.000000,0.000000,0.000000
month_12,22334728.88,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.002014,0.001628,0.001302,0.001022,0.000779,0.000562,0.000364,0.000000,0.000000,0.000000
month_13,22393345.39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001297,0.001036,0.000824,0.000650,0.000505,0.000381,0.000273,0.000176,0.000000,0.000000
month_14,24671655.23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.001116,0.000883,0.000699,0.000553,0.000434,0.000335,0.000252,0.000180,0.000115,0.000000
month_15,25478232.23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.002227,0.001792,0.001445,0.001164,0.000933,0.000741,0.000579,0.000439,0.000316,0.000204
month_16,25878820.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.002142,0.001711,0.001372,0.001102,0.000885,0.000708,0.000561,0.000438,0.000331,0.000238
month_17,25887161.41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.003804,0.003103,0.002538,0.002079,0.001703,0.001391,0.001129,0.000907,0.000715,0.000546
month_18,27699586.46,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.002547,0.002020,0.001611,0.001291,0.001038,0.000837,0.000673,0.000540,0.000429,0.000335
month_19,29872889.68,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.003847,0.003094,0.002501,0.002031,0.001655,0.001351,0.001103,0.000898,0.000727,0.000583
month_20,30482978.52,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.004524,0.003603,0.002887,0.002326,0.001882,0.001529,0.001245,0.001014,0.000824,0.000666

# Task 4

In [3982]:
cashflow = loans.copy()

In [3983]:
column_names = np.array(cashflow.columns)[1:]
origination = loans["Origination"]

In [3984]:
for col in column_names:
    cashflow[col] = loans[col] * origination

In [3985]:
cashflow

,Origination,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,...,month_35,month_36,month_37,month_38,month_39,month_40,month_41,month_42,month_43,month_44
month_1,10018746.17,1443069.08,3332200.33,1328138.75,928085.74,736418.27,539403.31,427557.86,324459.32,237056.39,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_2,10868379.04,0.00,1392751.60,3011884.91,1237868.70,970929.28,892351.83,668767.02,505612.59,419598.74,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_3,10733932.61,0.00,0.00,1537650.24,2953335.55,1208316.08,879375.19,711016.84,658251.40,503465.03,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_4,12558727.02,0.00,0.00,0.00,1617681.94,4082016.00,1387474.94,1247623.59,886293.35,694348.63,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_5,14505071.44,0.00,0.00,0.00,0.00,1992242.84,3930445.60,1394620.78,1227905.58,939424.54,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_6,15652952.20,0.00,0.00,0.00,0.00,0.00,2289453.76,4682354.31,1659503.89,1165897.09,...,5044.706791,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_7,15107713.30,0.00,0.00,0.00,0.00,0.00,0.00,2162283.09,4637701.69,1576348.23,...,7634.221455,4934.811087,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_8,17004745.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2402403.37,4947764.21,...,15035.587301,10844.467850,7022.231908,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_9,16794379.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2502066.86,...,20727.778843,15819.267111,11428.118454,7409.100362,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_10,19217205.82,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,19234.219560,15010.556685,11372.831189,8168.550233,5272.983180,0.000000,0.000000,0.000000,0.000000,0.000000
month_11,21628095.29,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,41792.142832,33445.260950,26285.206979,20031.069344,14453.845431,9362.550420,0.000000,0.000000,0.000000,0.000000
month_12,22334728.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,44982.539099,36351.087015,29072.235880,22836.033621,17394.810630,12547.096282,8125.193389,0.000000,0.000000,0.000000
month_13,22393345.39,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,29045.658146,23190.758152,18455.017340,14565.042171,11312.859886,8537.803928,6113.314052,3937.167545,0.000000,0.000000
month_14,24671655.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,27529.161071,21780.537992,17252.453061,13634.205809,10696.031845,8265.734651,6212.172124,4433.440517,2848.280719,0.000000
month_15,25478232.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,56735.123242,45669.416325,36816.896210,29652.119426,23777.690047,18890.021025,14754.375338,11186.528042,8039.146254,5191.520291
month_16,25878820.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,55424.411087,44280.836722,35510.245952,28531.188222,22910.961440,18324.597662,14525.458392,11324.009985,8572.368213,6152.913536
month_17,25887161.41,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,98463.380321,80317.702507,65700.355485,53823.347457,44081.131941,36005.490084,29231.669077,23472.923568,18501.295194,14133.003764
month_18,27699586.46,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,70555.654820,55940.571784,44618.303154,35761.818630,28763.182793,23172.108871,18652.275344,14950.130692,11872.482946,9270.279768
month_19,29872889.68,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,114907.133958,92425.710742,74725.419114,60677.652116,49433.490170,40350.968432,32941.580836,26830.916170,21729.620788,17411.887380
month_20,30482978.52,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,137893.735498,109821.803885,87995.197250,70891.668127,57378.270629,46607.790333,37943.060838,30901.734893,25115.937019,20302.697872

# Task 5

- Calculate values with the annual discount rate
- Monthly rates will be different (1 + n/12)^(1/12)

In [3986]:
annual_rate = 0.025
monthly_rate = (1 + annual_rate) ** (1 / 12) - 1

In [3987]:
predicted = np.array(cashflow.columns)[21:]

In [3988]:
predicted

array(['month_21', 'month_22', 'month_23', 'month_24', 'month_25',
       'month_26', 'month_27', 'month_28', 'month_29', 'month_30',
       'month_31', 'month_32', 'month_33', 'month_34', 'month_35',
       'month_36', 'month_37', 'month_38', 'month_39', 'month_40',
       'month_41', 'month_42', 'month_43', 'month_44'], dtype=object)

In [3989]:
for i in range(len(predicted)):
    cashflow[predicted[i]] = cashflow[predicted[i]] / (monthly_rate + 1) ** i

In [3990]:
cashflow

,Origination,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,...,month_35,month_36,month_37,month_38,month_39,month_40,month_41,month_42,month_43,month_44
month_1,10018746.17,1443069.08,3332200.33,1328138.75,928085.74,736418.27,539403.31,427557.86,324459.32,237056.39,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_2,10868379.04,0.00,1392751.60,3011884.91,1237868.70,970929.28,892351.83,668767.02,505612.59,419598.74,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_3,10733932.61,0.00,0.00,1537650.24,2953335.55,1208316.08,879375.19,711016.84,658251.40,503465.03,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_4,12558727.02,0.00,0.00,0.00,1617681.94,4082016.00,1387474.94,1247623.59,886293.35,694348.63,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_5,14505071.44,0.00,0.00,0.00,0.00,1992242.84,3930445.60,1394620.78,1227905.58,939424.54,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_6,15652952.20,0.00,0.00,0.00,0.00,0.00,2289453.76,4682354.31,1659503.89,1165897.09,...,4901.451988,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_7,15107713.30,0.00,0.00,0.00,0.00,0.00,0.00,2162283.09,4637701.69,1576348.23,...,7417.432069,4784.821051,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_8,17004745.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2402403.37,4947764.21,...,14608.620942,10514.858043,6794.800040,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_9,16794379.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2502066.86,...,20139.171022,15338.451856,11057.991355,7154.401933,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
month_10,19217205.82,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,18688.024421,14554.321602,11004.494700,7887.744627,5081.250292,0.000000,0.000000,0.000000,0.000000,0.000000
month_11,21628095.29,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,40605.369166,32428.716278,25433.897338,19342.472665,13928.283822,9003.569390,0.000000,0.000000,0.000000,0.000000
month_12,22334728.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,43705.167583,35246.221849,28130.661606,22051.012280,16762.311500,12066.012672,7797.593616,0.000000,0.000000,0.000000
month_13,22393345.39,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,28220.847072,22485.891724,17857.307222,14064.347999,10901.508812,8210.445515,5866.831267,3770.657900,0.000000,0.000000
month_14,24671655.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,26747.414044,21118.534192,16693.690879,13165.510469,10307.109483,7948.807979,5961.703479,4245.942627,2722.214671,0.000000
month_15,25478232.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,55124.012979,44281.327236,35624.492486,28632.785379,22913.100682,18165.735557,14159.493496,10713.430367,7683.330411,4951.542152
month_16,25878820.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,53850.521186,42934.952512,34360.161239,27550.387789,22077.887514,17621.991785,13939.806255,10845.097960,8192.951752,5868.494972
month_17,25887161.41,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,95667.310558,77876.503660,63572.491471,51973.092850,42478.281632,34624.959422,28053.077049,22480.212914,17682.420437,13479.705354
month_18,27699586.46,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,68552.082199,54240.298306,43173.232106,34532.454928,27717.314086,22283.638620,17900.234023,14317.863733,11347.002082,8841.760882
month_19,29872889.68,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,111644.110062,89616.497686,72305.256711,58591.770975,47636.020787,38803.822453,31613.408830,25696.190184,20767.859043,16607.022503
month_20,30482978.52,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,133977.959876,106483.849079,85145.261170,68454.665567,55291.918151,44820.743871,36413.234098,29594.846922,24004.295558,19364.205216